language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v2.1.0"
sudo: false

secure: "DHKMdirJD4ZAsnkCNXFQCYV2SwmF7Kqna5CqQkJYgjguXwK+PlXWzG+MvKG6Xs7jvoTPLdy3Tmbx83QDj1IOifEWDCh8r+qmPFYhNmHWEXnill3oLonH/aaZyU1Te9af3PqxDSy9X62L8yLVedPsyljWbw+EhgfniJtPTNEsMgRg0eTh4jf27h41O0/rV8P7+cd+7WOJhqc734IaECwHYg5MDDZpfQpxez4esLyT06T0scHuQs9JW6uVhyBcw7DhXQxAZzaMXoVz+Z3+9QhMsSTcf5hdfZCSunmJCVmyCiaAgXt7W7GTzOA6bErRdZ+BnUpPYVEaCD5HfP9I3+o1gg5OQDYPR4h9c5CM/zx/8rcgRfSmC2fKgB6q1nHoH050JnBo0N2BG0nsUW3EAdg0SdPwHHm3/ei7V6NFHrwhy4veXnFAuSavd80i12ogVz8fq8dTQ+Z5gcYyJ21/udRfkn/qMr6fDDggdIAWjA2hsiRcw9Inj40IhHoDmYnTU9vqdtXQJiVzxEq7M9T/GPeOHBnPAKeGlnDCRbf+8hlR/ivTbG5cggM73YUX3TBYAmBhpAkvPDwUd4v2JXtKVtvdWZmnbagvXQyfgGAy7zk8DR9SD+kK6rzpDIKCZU44v51LR3v0JZjg37xZvx/Z7Y5+j9w1LfpBkMxECGy3tGuRpp0="

# Build lifecycle
before_install: cd package
install: npm install
script: npm run compile
after_success: npm run coveralls