name             'buffer'
maintainer       'Joe McKie'
maintainer_email 'joe@joemck.ie'
license          'All rights reserved'
description      'Installs/Configures Buffer'
long_description 'Installs/Configures Buffer'
version          '0.1.0'

depends 'apt'
depends 'nodejs'