window.esdocSearchIndex = [
  [
    "buffer-node-api/src/client.js~bufferclient",
    "class/src/client.js~BufferClient.html",
    "<span>BufferClient</span> <span class=\"search-result-import-path\">buffer-node-api/src/client.js</span>",
    "class"
  ],
  [
    "buffer-node-api/src/modules/profile.js~profile",
    "class/src/modules/profile.js~Profile.html",
    "<span>Profile</span> <span class=\"search-result-import-path\">buffer-node-api/src/modules/profile.js</span>",
    "class"
  ],
  [
    "buffer-node-api/src/modules/update.js~update",
    "class/src/modules/update.js~Update.html",
    "<span>Update</span> <span class=\"search-result-import-path\">buffer-node-api/src/modules/update.js</span>",
    "class"
  ],
  [
    "buffer-node-api/src/utils.js~utils",
    "class/src/utils.js~Utils.html",
    "<span>Utils</span> <span class=\"search-result-import-path\">buffer-node-api/src/utils.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber21",
    "Core Suite",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber138",
    "Core Suite API Interaction",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber139",
    "Core Suite API Interaction Method: get",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber144",
    "Core Suite API Interaction Method: get should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber140",
    "Core Suite API Interaction Method: get should respond",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber150",
    "Core Suite API Interaction Method: get should use the GET method",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber157",
    "Core Suite API Interaction Method: post",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber162",
    "Core Suite API Interaction Method: post should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber158",
    "Core Suite API Interaction Method: post should respond",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber168",
    "Core Suite API Interaction Method: post should use the POST method",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber22",
    "Core Suite Authentication",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber72",
    "Core Suite Authentication Method: getAuthorizationUrl",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber73",
    "Core Suite Authentication Method: getAuthorizationUrl should include the client ID",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber77",
    "Core Suite Authentication Method: getAuthorizationUrl should include the redirect URI",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber23",
    "Core Suite Authentication should authenticate the user when returning from the OAuth gateway",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber84",
    "Core Suite Instantiation",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber109",
    "Core Suite Instantiation should assign the API protocol as HTTPS",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber105",
    "Core Suite Instantiation should assign the API version",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber97",
    "Core Suite Instantiation should assign the access token",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber85",
    "Core Suite Instantiation should assign the authenticated flag",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber89",
    "Core Suite Instantiation should assign the client ID",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber93",
    "Core Suite Instantiation should assign the client secret",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber117",
    "Core Suite Instantiation should assign the host in the format \"#{protocol}://#{hostname}\"",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber113",
    "Core Suite Instantiation should assign the hostname as \"api.bufferapp.com\"",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber101",
    "Core Suite Instantiation should assign the redirect_url",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber128",
    "Core Suite Instantiation should generate the OAuth client",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber132",
    "Core Suite Instantiation should retrieve the Buffer configuration",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber121",
    "Core Suite Instantiation should set the options to be passed to querystring.stringify()",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber177",
    "Core Suite Profiles",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber201",
    "Core Suite Profiles Method: getProfile",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber202",
    "Core Suite Profiles Method: getProfile should respond",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber206",
    "Core Suite Profiles Method: getProfile should retrieve the list of profiles",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber178",
    "Core Suite Profiles Method: getProfiles",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber189",
    "Core Suite Profiles Method: getProfiles should associate the profiles with the client",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber195",
    "Core Suite Profiles Method: getProfiles should instantiate each profile with the Profile object",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber183",
    "Core Suite Profiles Method: getProfiles should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/core/client.js.html#lineNumber179",
    "Core Suite Profiles Method: getProfiles should respond",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber1",
    "Module: Profile",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber11",
    "Module: Profile Instantiation",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber17",
    "Module: Profile Instantiation should assign the updates object structure",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber26",
    "Module: Profile Instantiation should be able to be instantiated with a profile ID",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber34",
    "Module: Profile Instantiation should be able to be instantiated with a profile object",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber59",
    "Module: Profile Method: getPendingUpdates",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber89",
    "Module: Profile Method: getPendingUpdates should associate the pending updates with the profile",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber96",
    "Module: Profile Method: getPendingUpdates should instantiate each update with the Update object",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber82",
    "Module: Profile Method: getPendingUpdates should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber161",
    "Module: Profile Method: getSchedules",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber169",
    "Module: Profile Method: getSchedules should associate the schedules with the profile",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber162",
    "Module: Profile Method: getSchedules should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber106",
    "Module: Profile Method: getSentUpdates",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber144",
    "Module: Profile Method: getSentUpdates should associate the sent updates with the profile",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber151",
    "Module: Profile Method: getSentUpdates should instantiate each update with the Update object",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber137",
    "Module: Profile Method: getSentUpdates should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber198",
    "Module: Profile Method: reorderUpdates",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber222",
    "Module: Profile Method: reorderUpdates should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber177",
    "Module: Profile Method: setSchedules",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber183",
    "Module: Profile Method: setSchedules should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber190",
    "Module: Profile Method: setSchedules should update the schedules associated with the profile",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber238",
    "Module: Profile Method: shuffleUpdates",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber262",
    "Module: Profile Method: shuffleUpdates should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber269",
    "Module: Profile Method: shuffleUpdates should return successful",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber45",
    "Module: Profile Property: pending_updates",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber46",
    "Module: Profile Property: pending_updates should retrieve the pending update list",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber52",
    "Module: Profile Property: sent_updates",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/profile.js.html#lineNumber53",
    "Module: Profile Property: sent_updates should retrieve the sent update list",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber1",
    "Module: Update",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber6",
    "Module: Update Instantiation",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber12",
    "Module: Update Instantiation should be able to be instantiated with an update ID",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber32",
    "Module: Update Instantiation should be able to be instantiated with an update object",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber75",
    "Module: Update Method: destroy",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber91",
    "Module: Update Method: destroy should add an attribute to flag the update as destroyed",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber84",
    "Module: Update Method: destroy should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber99",
    "Module: Update Method: edit",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber125",
    "Module: Update Method: edit should change edit the update object to reflect the new values",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber117",
    "Module: Update Method: edit should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber160",
    "Module: Update Method: getInteractions",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber174",
    "Module: Update Method: getInteractions should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber182",
    "Module: Update Method: moveToTop",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber196",
    "Module: Update Method: moveToTop should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber45",
    "Module: Update Method: save",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber67",
    "Module: Update Method: save should assign the saved ID to the Update object",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber59",
    "Module: Update Method: save should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber133",
    "Module: Update Method: share",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber143",
    "Module: Update Method: share should not throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/modules/update.js.html#lineNumber150",
    "Module: Update Method: share should retrieve the shared update and map it to the current object",
    "test"
  ],
  [
    "",
    "test-file/tests/core/utils.js.html#lineNumber1",
    "Utility Suite",
    "test"
  ],
  [
    "",
    "test-file/tests/core/utils.js.html#lineNumber2",
    "Utility Suite Method: mapObject",
    "test"
  ],
  [
    "",
    "test-file/tests/core/utils.js.html#lineNumber15",
    "Utility Suite Method: mapObject should copy the parameters from the full object to the empty object",
    "test"
  ],
  [
    "",
    "test-file/tests/core/utils.js.html#lineNumber22",
    "Utility Suite Method: shuffleArray",
    "test"
  ],
  [
    "",
    "test-file/tests/core/utils.js.html#lineNumber26",
    "Utility Suite Method: shuffleArray should randomise the order of the array",
    "test"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/client.js~bufferclient#client",
    "class/src/client.js~BufferClient.html#instance-member-client",
    "src/client.js~BufferClient#client",
    "member"
  ],
  [
    "src/client.js~bufferclient#config",
    "class/src/client.js~BufferClient.html#instance-member-config",
    "src/client.js~BufferClient#config",
    "member"
  ],
  [
    "src/client.js~bufferclient#constructor",
    "class/src/client.js~BufferClient.html#instance-constructor-constructor",
    "src/client.js~BufferClient#constructor",
    "method"
  ],
  [
    "src/client.js~bufferclient#deauthorizeuser",
    "class/src/client.js~BufferClient.html#instance-method-deauthorizeUser",
    "src/client.js~BufferClient#deauthorizeUser",
    "method"
  ],
  [
    "src/client.js~bufferclient#get",
    "class/src/client.js~BufferClient.html#instance-method-get",
    "src/client.js~BufferClient#get",
    "method"
  ],
  [
    "src/client.js~bufferclient#getaccesstoken",
    "class/src/client.js~BufferClient.html#instance-method-getAccessToken",
    "src/client.js~BufferClient#getAccessToken",
    "method"
  ],
  [
    "src/client.js~bufferclient#getconfiguration",
    "class/src/client.js~BufferClient.html#instance-method-getConfiguration",
    "src/client.js~BufferClient#getConfiguration",
    "method"
  ],
  [
    "src/client.js~bufferclient#getprofile",
    "class/src/client.js~BufferClient.html#instance-method-getProfile",
    "src/client.js~BufferClient#getProfile",
    "method"
  ],
  [
    "src/client.js~bufferclient#getprofiles",
    "class/src/client.js~BufferClient.html#instance-method-getProfiles",
    "src/client.js~BufferClient#getProfiles",
    "method"
  ],
  [
    "src/client.js~bufferclient#post",
    "class/src/client.js~BufferClient.html#instance-method-post",
    "src/client.js~BufferClient#post",
    "method"
  ],
  [
    "src/client.js~bufferclient#promise",
    "class/src/client.js~BufferClient.html#instance-member-promise",
    "src/client.js~BufferClient#promise",
    "member"
  ],
  [
    "src/client.js~bufferclient.getauthorizationurl",
    "class/src/client.js~BufferClient.html#static-method-getAuthorizationUrl",
    "src/client.js~BufferClient.getAuthorizationUrl",
    "method"
  ],
  [
    "src/modules/profile.js",
    "file/src/modules/profile.js.html",
    "src/modules/profile.js",
    "file"
  ],
  [
    "src/modules/profile.js~profile#constructor",
    "class/src/modules/profile.js~Profile.html#instance-constructor-constructor",
    "src/modules/profile.js~Profile#constructor",
    "method"
  ],
  [
    "src/modules/profile.js~profile#getbyid",
    "class/src/modules/profile.js~Profile.html#instance-method-getByID",
    "src/modules/profile.js~Profile#getByID",
    "method"
  ],
  [
    "src/modules/profile.js~profile#getpendingupdates",
    "class/src/modules/profile.js~Profile.html#instance-method-getPendingUpdates",
    "src/modules/profile.js~Profile#getPendingUpdates",
    "method"
  ],
  [
    "src/modules/profile.js~profile#getschedules",
    "class/src/modules/profile.js~Profile.html#instance-method-getSchedules",
    "src/modules/profile.js~Profile#getSchedules",
    "method"
  ],
  [
    "src/modules/profile.js~profile#getsentupdates",
    "class/src/modules/profile.js~Profile.html#instance-method-getSentUpdates",
    "src/modules/profile.js~Profile#getSentUpdates",
    "method"
  ],
  [
    "src/modules/profile.js~profile#pending_updates",
    "class/src/modules/profile.js~Profile.html#instance-get-pending_updates",
    "src/modules/profile.js~Profile#pending_updates",
    "member"
  ],
  [
    "src/modules/profile.js~profile#promise",
    "class/src/modules/profile.js~Profile.html#instance-member-promise",
    "src/modules/profile.js~Profile#promise",
    "member"
  ],
  [
    "src/modules/profile.js~profile#reorderupdates",
    "class/src/modules/profile.js~Profile.html#instance-method-reorderUpdates",
    "src/modules/profile.js~Profile#reorderUpdates",
    "method"
  ],
  [
    "src/modules/profile.js~profile#schedules",
    "class/src/modules/profile.js~Profile.html#instance-member-schedules",
    "src/modules/profile.js~Profile#schedules",
    "member"
  ],
  [
    "src/modules/profile.js~profile#sent_updates",
    "class/src/modules/profile.js~Profile.html#instance-get-sent_updates",
    "src/modules/profile.js~Profile#sent_updates",
    "member"
  ],
  [
    "src/modules/profile.js~profile#setschedules",
    "class/src/modules/profile.js~Profile.html#instance-method-setSchedules",
    "src/modules/profile.js~Profile#setSchedules",
    "method"
  ],
  [
    "src/modules/profile.js~profile#shuffleupdates",
    "class/src/modules/profile.js~Profile.html#instance-method-shuffleUpdates",
    "src/modules/profile.js~Profile#shuffleUpdates",
    "method"
  ],
  [
    "src/modules/profile.js~profile#updates",
    "class/src/modules/profile.js~Profile.html#instance-member-updates",
    "src/modules/profile.js~Profile#updates",
    "member"
  ],
  [
    "src/modules/update.js",
    "file/src/modules/update.js.html",
    "src/modules/update.js",
    "file"
  ],
  [
    "src/modules/update.js~update#constructor",
    "class/src/modules/update.js~Update.html#instance-constructor-constructor",
    "src/modules/update.js~Update#constructor",
    "method"
  ],
  [
    "src/modules/update.js~update#destroy",
    "class/src/modules/update.js~Update.html#instance-method-destroy",
    "src/modules/update.js~Update#destroy",
    "method"
  ],
  [
    "src/modules/update.js~update#destroyed",
    "class/src/modules/update.js~Update.html#instance-member-destroyed",
    "src/modules/update.js~Update#destroyed",
    "member"
  ],
  [
    "src/modules/update.js~update#edit",
    "class/src/modules/update.js~Update.html#instance-method-edit",
    "src/modules/update.js~Update#edit",
    "method"
  ],
  [
    "src/modules/update.js~update#getbyid",
    "class/src/modules/update.js~Update.html#instance-method-getByID",
    "src/modules/update.js~Update#getByID",
    "method"
  ],
  [
    "src/modules/update.js~update#getinteractions",
    "class/src/modules/update.js~Update.html#instance-method-getInteractions",
    "src/modules/update.js~Update#getInteractions",
    "method"
  ],
  [
    "src/modules/update.js~update#movetotop",
    "class/src/modules/update.js~Update.html#instance-method-moveToTop",
    "src/modules/update.js~Update#moveToTop",
    "method"
  ],
  [
    "src/modules/update.js~update#promise",
    "class/src/modules/update.js~Update.html#instance-member-promise",
    "src/modules/update.js~Update#promise",
    "member"
  ],
  [
    "src/modules/update.js~update#save",
    "class/src/modules/update.js~Update.html#instance-method-save",
    "src/modules/update.js~Update#save",
    "method"
  ],
  [
    "src/modules/update.js~update#share",
    "class/src/modules/update.js~Update.html#instance-method-share",
    "src/modules/update.js~Update#share",
    "method"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "src/utils.js~utils.mapobject",
    "class/src/utils.js~Utils.html#static-method-mapObject",
    "src/utils.js~Utils.mapObject",
    "method"
  ],
  [
    "src/utils.js~utils.shufflearray",
    "class/src/utils.js~Utils.html#static-method-shuffleArray",
    "src/utils.js~Utils.shuffleArray",
    "method"
  ],
  [
    "tests/core/client.js",
    "test-file/tests/core/client.js.html",
    "tests/core/client.js",
    "testFile"
  ],
  [
    "tests/core/utils.js",
    "test-file/tests/core/utils.js.html",
    "tests/core/utils.js",
    "testFile"
  ],
  [
    "tests/globals.js",
    "test-file/tests/globals.js.html",
    "tests/globals.js",
    "testFile"
  ],
  [
    "tests/modules/profile.js",
    "test-file/tests/modules/profile.js.html",
    "tests/modules/profile.js",
    "testFile"
  ],
  [
    "tests/modules/update.js",
    "test-file/tests/modules/update.js.html",
    "tests/modules/update.js",
    "testFile"
  ]
]